language: python
python:
  - 3.4
  - 3.5

install:
    - pip install coveralls -r requirements-dev.txt -e .

script:
    make cov
after_success:
    coveralls

env:
  matrix:
    - PYTHONASYNCIODEBUG=1
    - PYTHONASYNCIODEBUG=0
