language: python
python:
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install -r requirements-dev.txt
    - pip install codecov
script:
    make cov
after_success:
    codecov
env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=0
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: jettify
    password:
        secure: V/UjH36QQcJyLqIzNb7/R1Y4nLJi1O2nvp/xf3O/myiO722QD6SZQ7u5CoWcicyQBhqodu/oXA2XeJk1LAorhKnk15CkiWhO7wFAWuYc4rQA7qgjApfercGPqcSL1K2RmGeP/UWpLR+La5o4/9zCmfG83Z007rmii9a6dbdJU7c=
    on:
        tags: true
        repo: aio-libs/aiohttp_sse
        all_branches: true
        python: 3.5
